src/P4M/CoreBundle/Entity/Image.php
<?php

namespace P4M\CoreBundle\Entity;

use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\Groups;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Image
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="P4M\CoreBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Groups({"info","json", "donator"})
     * @Accessor(getter="getWebPath")
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     * @Groups({"json"})
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

//    @Assert\NotBlank(message="Please choose a picture")
    /**
     *
     * @var type 
     * 
     * @Assert\Image(maxSize = "1024k",maxSizeMessage="Filesize Maximum 1Mo")
     */
    private $file;
    private $tempFilename ;

    private $set = false;

    private $forced = false;

    private $localPath;




    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    /*
     * Should only be used for default pictures
     */
    public function forceId($forcedId)
    {
        $this->id = $forcedId;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Image
     */
    public function setName($name)
    {
        $this->name = $name;
        
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;
    
        return $this;
    }

    /**
     * Get alt
     *
     * @return string 
     */
    public function getAlt()
    {
        return $this->alt;
    }
    
    
    public function getFile()
    {
        return $this->file;
    }
    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
  
    public function setFile(UploadedFile $file)
    {
        
        $this->file = $file;
    
    
    // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->name) {
          // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->name;

            // On réinitialise les valeurs des attributs name et alt
            $this->name = null;
            $this->alt = null;
        }
        $this->set = true;
    }
    
    public function getSet()
    {
        return $this->set;
    }

  /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
  public function preUpload()
  {
      
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
          return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->name = $this->file->guessExtension();

    //    die($this->name);
        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
  }

  /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
  public function upload()
  {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
          return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
          $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
          if (file_exists($oldFile)) {
            unlink($oldFile);
          }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
          $this->getUploadRootDir(), // Le répertoire de destination
          $this->id.'.'.$this->name   // Le nom du fichier à créer, ici « id.extension »
        );
      
        chmod( $this->getUploadRootDir().'/'.$this->id.'.'.$this->name, 0777);
  }

  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->name;
  }

  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }

  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur
    return 'images/uploads';
  }

  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }
  
  public function getWebPath()
  {
    return $this->getUploadDir().'/'.$this->getId().'.'.$this->getName();
  }

  public function forceLocalPicture($path)
  {
        $this->forced = true;
        $this->localPath = $path;
         $pathInfo = pathinfo($this->localPath);
        $this->name = $pathInfo['extension'];
        $this->alt = $pathInfo['basename'];
}
  
  /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
  
    public function copyFromLocal()
    {
        if ($this->forced == true)
        {   
            $dest = $this->getUploadRootDir().'/'.$this->id.'.'.$this->name;
            copy($this->localPath, $dest);
            chmod($dest, 0644);
        }
    }

    function __toString()
    {
        return $this->getWebPath();
    }

}

src/P4M/CoreBundle/Resources/views/Menu/menu.html.twig
<div id="menu" class="navigation" role="navigation">
    <div id="left-menu">
        <ul class="p4m-menu">
            {% if user is defined and user is not null and user.enabled %}
                <li id="menu-sidebar-btn" class="menu-item">
                    <a id="sidebar-btn" class="tooltip-menu-icon menu-item-icon" href="#back" data-original-title=""
                       title="">
                        <span class="non-hover-glyph icon-strew"></span>
                        <span class="hover-glyph glyphicon left_arrow"></span>
                    </a>
                    {{ render(controller('P4MCoreBundle:Core:shortcutBar')) }}
                    {#                    {% include "P4MCoreBundle:Menu:shortcut-bar.html.twig"%}#}
                </li>
            {% endif %}
            <li class="menu-item">
                <a id="search-icon" href="#search" class="menu-item-icon tooltip-menu-icon"
                   title="{{ 'Look for something'|trans({},'menu') }}"><span class="glyphicon search"></span></a>
            </li>

            {% if user is defined and user %}
                <li class="menu-item">
                    <a id="add-post-icon" href="#addPost" class="menu-item-icon tooltip-menu-icon"
                       title="{{ 'Add new content'|trans({}, 'menu') }}"><span class="glyphicon plus"></span></a>
                </li>
            {% else %}
                <li class="menu-item">
                    <a id="add-post-icon" href="#addPost" class="menu-item-icon tooltip-menu-icon" data-toggle="modal"
                       data-target="#modal-register" title="{{ 'Add new content'|trans({}, 'menu') }}"><span
                                class="glyphicon plus"></span></a>
                </li>
            {% endif %}
        </ul>

        <!--Formulaire caché -->
        {% if user is defined and user %}
            <form id="add-post-form" class="menu-form" autocomplete="off">
                <input type="text"
                       placeholder="{{ 'Paste here any URL to share your favorite content on Pressformore'|trans({}, 'menu') }}"
                       name="post-url" class="menu-form-field " id="addPostUrl"/>
                <button class="menu-form-icon ajax_action" data-target="{{ ['addPostUrl']|json_encode() }}"
                        data-action="addPost" data-url="{{ path('p4m_ajax_action') }}"
                        data-key="{{ 'addPost'|sha512 }}"><span class="glyphicon edit"></span></button>
            </form>
        {% endif %}

        <form id="menu-search-form"
              class="menu-form{% if keyword is defined and keyword|length>0 %} force-open{% endif %}"
              action="{{ path("p4m_core_search") }}" autocomplete="off">
            <input type="text" placeholder="{{ 'Find an articles, author..'|trans({}, 'menu') }}" name="k"
                   class="menu-form-field"
                   {% if keyword is defined and keyword|length>0 %}value="{{ keyword|trans({}, 'menu') }}"{% endif %}>

            <select class="menu-form-select" name="where">
                <option data-icon="glyphicon star" value="all">{{ 'All'|trans({}, 'menu') }}</option>
                <option data-icon="glyphicon user" value="user">{{ 'People'|trans({}, 'menu') }}</option>
                <option data-icon="glyphicon show_thumbnails" value="strew">{{ 'Strew'|trans({}, 'menu') }}</option>
                <option data-icon="glyphicon file" value="post">{{ 'Content'|trans({}, 'menu') }}</option>
            </select>
            <button class="menu-form-icon"><span class="glyphicon search"></span></button>
        </form>

    </div>

    <div id="center-menu">
        <div id="center-menu-left-zone">
            <ul class="p4m-menu">
                <li class="menu-item hide-menu-item">
                    <a class="menu-item-text"
                       href="{{ path('p4m_core_home') }}#resume">{{ 'Values'|trans({}, 'menu') }}</a>

                </li>
                <li class="menu-item hide-menu-item">
                    <a class="menu-item-text" href="#follow-us" id="menu-social-links" data-html="true"
                    >{{ 'Follow Us'|trans({}, 'menu') }}</a>

                    <div class="hidden">
                        <a href='https://www.facebook.com/Pressformore' target='_blank'><img
                                    src='{{ asset('images/social_icons/facebook-icon.png') }}'
                                    alt='Faceboook icon'/></a>
                        <a href='https://twitter.com/pressformore_' target='_blank'><img
                                    src='{{ asset('images/social_icons/twitter-icon.png') }}' alt='Twitter icon'/></a>
                        <a href='http://www.pinterest.com/pressformore/' target='_blank'><img
                                    src='{{ asset('images/social_icons/pinterest-icon.png') }}'
                                    alt='Pinterest icon'/></a>
                        <a href='https://plus.google.com/101006798117217795155/' target='_blank'><img
                                    src='{{ asset('images/social_icons/google+_icon.png') }}' alt='Google+ icon'/></a>
                    </div>
                </li>
            </ul>
        </div>

        <div class="menu-item" id="menu-logo">
            <a class="menu-item-pic"
               href="{% if app.user %}{{ path('p4_m_backoffice_homepage') }}{% else %}{{ path('p4m_core_home') }}{% endif %}">
                <img alt="{{ 'Logo Pressformore, the first crowd-shaped media'|trans({}, 'menu') }}"
                     src="{{ asset('images/design/logo-big.png') }}">
            </a>
        </div>

        <div id="center-menu-right-zone">
            <ul class="p4m-menu">
                <li class="menu-item hide-menu-item">
                    <a class="menu-item-text"
                       href="{{ path('p4m_core_home') }}#legal-mention">{{ 'Legal'|trans({}, 'menu') }}</a>
                </li>
                <li class="menu-item hide-menu-item">
                    <a class="menu-item-text"
                       href="{{ path('p4m_core_home') }}#contact">{{ 'Contact'|trans({}, 'menu') }}</a>
                </li>
            </ul>
        </div>
    </div>

    <div id="right-menu">
        <ul class="p4m-menu">
            {% if user is defined and user %}
                <li class="menu-item" id="user-menu-pic">
                    <a class="menu-item-text  tooltip-menu-icon" title="{{ 'View your profile'|trans({},'menu') }}"
                       href="{{ path('p4m_social_profile',{username:user.username} ) }}">
                        <img class="thumb-align"
                             src="{% if user.picture %}{{ asset(user.picture.webPath) }}{% else %}{{ asset('images/users/defaultUser.jpg') }}{% endif %}"
                             alt="{{ user.username }}"/>

                    </a>
                </li>

                {% include "P4MCoreBundle:Menu/Notification:notification-menu.html.twig" %}


                <li class="menu-item">
                    <a class="menu-item-icon   tooltip-menu-icon" title="{{ 'Help me!'|trans({}, 'menu') }}"
                       id="help-me" href="#help">
                        <span class="glyphicon life_preserver"></span>
                    </a>
                </li>

                <li class="menu-item">
                    <a class="menu-item-icon   tooltip-menu-icon" title="{{ 'Disconnect'|trans({}, 'menu') }}"
                       href="{{ path('fos_user_security_logout') }}">
                        <span class="glyphicon power"></span>
                    </a>
                </li>
            {% else %}
                {#<li class="menu-item">
                    <a class="menu-item-text" title="Login" href="{{path('fos_user_registration_register')}}">
                        Register
                    </a>
                </li>#}

                {#            <li class="menu-item">#}
                {#                    <a class="main-button-link" id="join-beta" href="#beta-coming-soon"  data-toggle="modal" data-target="#modal-join-us">Request an access!</a>#}
                {#            </li>#}

                <li class="menu-item">
                    <a class="main-button-link"
                       href="{{ path('fos_user_security_login') }}">{{ 'Log in'|trans({},'menu') }}</a>

                </li>
            {% endif %}


        </ul>
    </div>

</div>

<!-- mainmenu-block-bg -->
<!-- END MAIN MENU -->

src/P4M/CoreBundle/Resources/views/Menu/shortcut-bar.html.twig
<nav id="user-sidebar" data-status="close">
    <div class="sidebar-list-block">
        <ul class="sidebar-list">
            <li class="sidebar-item">
                <a href="{{ path('p4m_core_wall') }}">
                    <span class="icon-strew"></span>{{ 'Home'|trans({}, 'menu')}}
                </a>
            </li>
            <li class="sidebar-item">
                <a href="{{ path('p4_m_blog_homepage') }}#featured-content"><span class="icon-strew"></span>
                    {{ 'Featured Content'|trans({}, 'menu')}}</a>
            </li>
        </ul>
    </div>
    <div class="sidebar-list-block">
        <h4 class="sidebar-list-title">{{ 'Your strews'|trans({}, 'menu')}}</h4>
        <ul class="sidebar-list">
            {% set newPostCount = 0 %}
            {% for wall in user.walls %}
                {#            {%set newPostCount = user|newPostCountByWall(wall)%}#}

                <li class="sidebar-item">
                    <a title="{{ wall.name }}" href="{{ path('p4m_core_showWall',{wallSlug:wall.slug}) }}"><span
                                class="icon-strew"></span><span
                                class="sidebar-wall-name">{{ wall.name }}</span>{% if newPostCount>0 %}<span
                                class="newPostNotifications">{{ newPostCount }}</span>{% endif %}</a>
                </li>

            {% endfor %}

            {% if user.wallsfollowed|length %}

                <li class="sidebar-item">
                    <h4 class="sidebar-list-title">{{ 'Followed strews'|trans({}, 'menu')}}</h4>
                </li>

                {% for wall in user.wallsFollowed %}
                    {#            {%set newPostCount = user|newPostCountByWall(wall)%}#}

                    <li class="sidebar-item">

                        <a title="{{ wall.name }}" href="{{ path('p4m_core_showWall',{wallSlug:wall.slug}) }}"><span
                                    class="icon-strew"></span><span
                                    class="sidebar-wall-name">{{ wall.name }}</span> {% if newPostCount>0 %}<span
                                    class="newPostNotifications">{{ newPostCount }}</span>{% endif %}</a>
                    </li>

                {% endfor %}
            {% endif %}
            {% if suggestedWalls|length %}
                <li class="sidebar-item">
                    <h4 class="sidebar-list-title">{{ 'Suggested strews'|trans({}, 'menu')}}</h4>
                </li>
                {% for wall in suggestedWalls %}
                    {#                {%set newPostCount = user|newPostCountByWall(wall)%}#}
                    <li class="sidebar-item">

                        <a title="{{ wall.name }}" href="{{ path('p4m_core_showWall',{wallSlug:wall.slug}) }}"><span
                                    class="icon-strew"></span><span
                                    class="sidebar-wall-name">{{ wall.name }}</span> {% if newPostCount>0 %}<span
                                    class="newPostNotifications">{{ newPostCount }}</span>{% endif %}</a>
                    </li>

                {% endfor %}
            {% endif %}

            <li class="sidebar-item-manage">
                <a href="{{ path('p4m_backoffice_wall_create') }}"><span class="glyphicon plus"></span>{{ 'Build a new strew'|trans({}, 'menu')}}</a><a
                        href="{{ path('p4_m_backoffice_homepage') }}"><span class="glyphicon wrench"></span>{{ 'Strew settings'|trans({}, 'menu')}}</a>
            </li>
        </ul>
    </div>

    {# <div class="sidebar-list-block">
             <h4>Suggested strews</h4>
             <ul class="sidebar-list">


             </ul>
     </div>#}
    <div class="sidebar-list-block">
        <!--<h4></h4>-->
        <ul class="sidebar-list">
            {#                {%set newPostCount = user.readLater|length%}#}
            <li class="sidebar-item">
                <a href="{{ path('p4m_core_showHistory') }}"><span class="glyphicon step_backward">&nbsp;</span>{{ 'History'|trans({}, 'menu')}}</a>
            </li>
            <li class="sidebar-item">
                <a href="{{ path('p4m_core_showReadLater') }}">
                    <span class="glyphicon clock">&nbsp;</span>
                    {{ 'Read later'|trans({}, 'menu')}} {% if newPostCount>0 %}<span class="newPostNotifications">{{ newPostCount }}</span>{% endif %}
                </a>
            </li>

        </ul>
    </div>

    {% if is_granted('ROLE_ADMIN') and post is defined %}
        <div class="sidebar-list-block">
            <!--<h4></h4>-->

            <ul class="sidebar-list">
                {% if post.showOnHome == false %}
                    <li class="sidebar-item">
                        <a href="#" data-url="{{ path('p4m_ajax_action') }}" class="ajax_action"
                           data-action="addPostToHome" data-params="{{ {postId:post.id}|json_encode() }}"
                           data-key="{{ {postId:post.id}|json_encode()|sha512() }}">
                            <span class="glyphicon step_backward">&nbsp;</span>{{ 'Show this post on home page'|trans({}, 'menu')}} </a>
                    </li>
                {% else %}
                    <li class="sidebar-item">
                        <a href="{{ path('p4m_ajax_action') }}" class="ajax_action" data-action="removePostFromHome"
                           data-params="{{ {postId:post.id}|json_encode() }}"
                           data-key="{{ {postId:post.id}|json_encode()|sha512() }}"><span
                                    class="glyphicon step_backward">&nbsp;</span>{{ 'Show this post on home page'|trans({}, 'menu')}}</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    {% endif %}
</nav>

